NUMPY

Declare the Numpy array

In [2]:
import numpy as np
a=np.array([1,2,3])
print(a)

[1 2 3]


Create an array with full of zero values


In [4]:
print(np.zeros(5))

[0. 0. 0. 0. 0.]


Create an array with a Scalar values filled



In [5]:
print(np.full(5, 10))

[10 10 10 10 10]


Create an array with random values


In [6]:
print(np.random.rand(5))

[0.53224899 0.30216979 0.45750517 0.83278467 0.40246593]


Reshape and Flattening the array.


In [7]:
a = np.array([[1,2],[3,4]])
print(a.reshape(4,1))
print(a.flatten())

[[1]
 [2]
 [3]
 [4]]
[1 2 3 4]


Convert an array from one type to another.



In [8]:
a = np.array([1.1, 2.2, 3.3])
print(a.astype('int'))

[1 2 3]


Do slicing operations in an array.


In [9]:
a = np.array([1, 2, 3, 4, 5])
print(a[1:4])

[2 3 4]


Do join functions (join,horizontal join,vertical join and depth join)

In [10]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(np.concatenate([a, b]))

[1 2 3 4 5 6]


Do index retrivel and basic operation with respect to index

In [11]:
a = np.array([1, 2, 3, 4, 5])
print(a[2])
a = np.array([1, 2, 3, 4, 5])
a[2] = 10
print(a)

3
[ 1  2 10  4  5]


Sorting operation of an array

In [12]:
a = np.array([5, 2, 3, 1, 4])
print(np.sort(a))

[1 2 3 4 5]


Filtering operation based on array value


In [13]:
a = np.array([1, 2, 3, 4, 5])
print(a[a > 2])

[3 4 5]


Vector Operation - Addition ,Subtraction, Multiplication and Division


In [14]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)
print(a - b)
print(a * b)
print(a / b)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


Scalar Operation and Vectorize operation.

In [15]:
a = np.array([1, 2, 3])
print(a + 2)
def myfunc(x):
  return x*2
a = np.array([1, 2, 3])
vfunc = np.vectorize(myfunc)
print(vfunc(a))

[3 4 5]
[2 4 6]


PANDAS

Declare Empty Dataframe

In [16]:
import pandas as pd
df = pd.DataFrame()
print(df)

Empty DataFrame
Columns: []
Index: []


Declare and print the DataFrame Series

In [17]:
import pandas as pd
s = pd.Series([1, 3, 5, np.nan, 6, 8])
print(s)

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64


Add one column and row.

In [18]:
import pandas as pd
df = pd.DataFrame()
df['new_column'] = [1, 2, 3]
print(df)

   new_column
0           1
1           2
2           3


Extract any one column and row based on condition

In [19]:
import pandas as pd
data = {'Name': ['Alice', 'Bob', 'Charlie'], 'Age': [25, 30, 28]}
df = pd.DataFrame(data)
name_column = df['Name']
print(name_column)

0      Alice
1        Bob
2    Charlie
Name: Name, dtype: object


Do the functions like Sum ,square root ,min,max functiion , sort and merge of values .


In [20]:
import pandas as pd
data = {'Value1': [1, 2, 3], 'Value2': [4, 5, 6]}
df = pd.DataFrame(data)
sum_values = df.sum()
print(sum_values)

Value1     6
Value2    15
dtype: int64


Create series from array , Dictionary

In [21]:
arr = np.array([1, 2, 3])
s = pd.Series(arr)
print(s)
d = {'a': 1, 'b': 2, 'c': 3}
s = pd.Series(d)
print(s)

0    1
1    2
2    3
dtype: int64
a    1
b    2
c    3
dtype: int64


Create Series using Scalar value,index.

In [22]:
import pandas as pd
s = pd.Series(5, index=[0, 1, 2, 3])
print(s)


0    5
1    5
2    5
3    5
dtype: int64


LOAD AND STORE

Create a dataframe and store the data into specific excel file

In [23]:
import pandas as pd
data = {'Name': ['Alice', 'Bob', 'Charlie'], 'Age': [25, 30, 28]}
df = pd.DataFrame(data)
df.to_excel('my_excel_file.xlsx', index=False)

Read and display the excel file data.

In [25]:
import pandas as pd
df = pd.read_excel('my_excel_file.xlsx')
print(df)


      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   28


Display the particular column values , row values and do slicing operations.


In [27]:
import pandas as pd
df = pd.read_excel('my_excel_file.xlsx')
name_column = df['Name']
print(name_column)

0      Alice
1        Bob
2    Charlie
Name: Name, dtype: object
